# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Senior Jack
email: jack12972@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Blog de tecnología y desarrollo de sofware.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  jack-factor

# Build settings
markdown: kramdown

# Theme settings
style: minimal               # choose between "default", "contrast" and "minimal"
dark_theme: false            # enables dark mode

navigation:                  # (optional) site navigation in the header
  # index.md
  # about.md


icons:                       # (optional) icons in the header, see http://fontawesome.com/icons
  # envelope: "mailto:"
  github: "https://github.com/jack-factor"
  rss: "/feed.xml"


remote_theme: niklasbuschmann/contrast
plugins:
  - jekyll-feed
  - jekyll-seo-tag 
  - jekyll-remote-theme
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
